services:
  mongo:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
      - 27017:27017

  backend:
    image: ricardodcpina/measure-reader-backend
    container_name: 'backend'
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - DATABASE_URL=mongodb://mongo:27017/measure-reader
    depends_on:
      - mongo
