services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  backend:
    build: .
    ports:
      - ${API_PORT:-3000}:${API_PORT:-3000}
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - API_PORT=${API_PORT}
      - DATABASE_URL=mongodb://admin:admin@mongo:27017/meter-scanner?authSource=admin
    depends_on:
      - mongo
