openapi: 3.0.0
info:
  title: MeterScanner API
  description: MeterScanner is a RESTful API designed to capture and record measurements from images of utility meters, such as water, gas and eletricity. By scanning images of these meters it automatically extracts measurements via Google Gemini LLM API and logs them into a database for accurate tracking and analysis.
  version: 1.0.0

servers:
  - url: https://meter-scanner-e5pk.onrender.com

paths:
  /upload:
    post:
      summary: Insert a new measurement
      description: Upload a base64-encoded image to extract its measurement via Google Gemini API and insert into database.

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: Base64
                  example: data:image/png;base64,iVBORw0KGgoAAAANSUhE...
                  description: Data URI for a Base64-encoded image of a water or gas meter
                customer_code:
                  type: string
                  example: 12345
                  description: Customer identifier
                measurement_datetime:
                  type: string
                  format: date
                  example: 2024-12-08
                  description: Date when the measurement was made
                measurement_type:
                  type: string
                  enum:
                    - 'WATER'
                    - 'GAS'
                  description: Type of measurement

      responses:
        '200':
          description: Measurement registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  image_url:
                    type: string
                    format: uri
                    example: 'http://some-domain/files/some-image.png'
                    description: Temporary URL link for acessing uploaded image
                  measurement_value:
                    type: number
                    example: 2738
                    description: Measurement extracted via Google Gemini API
                  measurement_uuid:
                    type: string
                    format: uuid
                    example: ddcb51fb-44d5-438f-b000-5c0fe697e1ed
                    description: Measurement identifier

        '400':
          description: Request body contains invalid data, such as fields containing wrong types or were not provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: INVALID_DATA
                  error_description:
                    type: string
                    example: Dados inválidos

        '409':
          description: Measurement has already been inserted for the given month
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: DOUBLE_REPORT
                  error_description:
                    type: string
                    example: Leitura do mês já realizada

  /confirm:
    patch:
      summary: Update an inserted measurement
      description: Confirm or rectify an inserted measurement and update database.

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                measurement_uuid:
                  type: string
                  format: uuid
                  example: 'bde81a6b-fee7-4842-bfae-d2182dbf9e77'
                  description: Measurement identifier
                confirmed_value:
                  type: number
                  example: 500
                  description: Confirmed value for measurement

      responses:
        '200':
          description: Measurement updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true

        '400':
          description: Request body contains invalid data, such as fields containing wrong types or were not provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: INVALID_DATA
                  error_description:
                    type: string
                    example: Dados inválidos

        '404':
          description: No measurement found with provided measurement_uuid
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: number
                    example: MEASUREMENT_NOT_FOUND
                  error_description:
                    type: string
                    example: Leitura não encontrada

        '409':
          description: Measurement has already been confirmed for the given month
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: CONFIRMATION_DUPLICATE
                  error_description:
                    type: string
                    example: Leitura do mês já confirmada

  /{customerId}/list:
    get:
      summary: List measurements from a customer
      description: List all measurement with an optional measurement type filter for a given customer. Water and gas are valid measurement types for the moment, but not eletricity. If no measurement type is provided, the list return all measurements disregarding the type.

      parameters:
        - in: path
          name: customerId
          required: true
          example: 4658855
          schema:
            type: string
          description: Customer identifier
        - in: query
          name: measurement_type
          schema:
            type: string
            enum:
              - WATER
              - GAS
              - ELETRICITY
          description: Type of measurement

      responses:
        '200':
          description: Measurements list obtained successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  customer_code:
                    type: string
                    example: 4658855
                    description: Customer identifier
                  measurements:
                    type: array
                    items:
                      type: object
                      properties:
                        measurement_uuid:
                          type: string
                          example: bde81a6b-fee7-4842-bfae-d2182dbf9e77
                          description: Measurement identifier
                        measurement_datetime:
                          type: string
                          format: date
                          example: 2024-12-08T00:00:00.000Z
                          description: Date the measurement was made
                        measurement_type:
                          type: string
                          enum:
                            - 'WATER'
                            - 'GAS'
                          description: Type of measurement
                        has_confirmed:
                          type: boolean
                          example: true
                          description: Indicates if measurement has been confirmed
                        image_url:
                          type: string
                          example: http://some-domain/files/some-image.png
                          description: Temporary URL link for acessing uploaded image

        '400':
          description: Measurement type filter provided is invalid (eletricity, for instance)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: INVALID_TYPE
                  error_description:
                    type: string
                    example: Tipo de medição não permitida

        '404':
          description: No measurements were found for the given customer
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: MEASUREMENTS_NOT_FOUND
                  error_description:
                    type: string
                    example: Nenhuma leitura encontrada
                    
components:
  schemas:
    Measurement:
      type: object
      required:
        - customer_code
        - measurement_uuid
        - measurement_value
        - measurement_datetime
        - measurement_type
      properties:
        customer_code:
          type: string
          example: 4658855
          description: Customer identifier
        measurement_uuid:
          type: string
          format: uuid
          example: ddcb51fb-44d5-438f-b000-5c0fe697e1ed
          description: Measurement identifier
        measurement_value:
          type: number
          example: 2738
          description: Measurement value extracted from Google Gemini API
        measurement_datetime:
          type: string
          format: date
          example: 2024-12-08
          description: Date when the measurement was made
        measurement_month:
          type: integer
          example: 11
          description: Month of measurement, where 0 is January
        measurement_type:
          type: string
          enum:
            - 'WATER'
            - 'GAS'
          description: Type of measurement
        has_confirmed:
          type: boolean
          example: false
          description: Indicates if measurement has been confirmed
        image_url:
          type: string
          format: url
          example: 'http://some-domain/files/some-image.png'
          description: Temporary URL link for acessing uploaded image